version: "3.1"

services:
  db:
    container_name: database
    image: sameersbn/postgresql:latest
    environment:
      DB_PASS: $PG_PASS
      DB_NAME: $PG_DB_NAME
      DB_USER: $PG_USER

    restart: always
    ports:
      - "5432:5432"
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  telegram_bot:
    container_name: rosatom_scedule_bot
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db

networks:
  botnet:
    driver: bridge